# Generated by Django 3.1.3 on 2021-04-11 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='answers',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='questions',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
