# Generated by Django 3.1.3 on 2021-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0002_auto_20210411_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='given_answer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
