# Generated by Django 3.1.3 on 2021-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0003_interviewdata_given_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='index_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
