# Generated by Django 3.1.3 on 2021-04-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0004_interviewdata_index_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='accuracy_eighty',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='accuracy_hundred',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
