# Generated by Django 3.1.3 on 2021-04-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0005_auto_20210415_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='accuracy_eighty',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='interviewdata',
            name='accuracy_hundred',
            field=models.JSONField(),
        ),
    ]
