# Generated by Django 3.1.3 on 2021-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0007_auto_20210417_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='accuracy_eighty',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewdata',
            name='accuracy_hundred',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
