# Generated by Django 3.1.3 on 2021-04-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0008_auto_20210417_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='accuracy_eighty',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewdata',
            name='accuracy_hundred',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
