# Generated by Django 3.1.3 on 2021-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0009_auto_20210417_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='isAnswerd',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
