# Generated by Django 3.1.3 on 2021-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0011_remove_interviewdata_isanswerd'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='isAnswerd',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
