# Generated by Django 3.1.3 on 2021-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0013_remove_interviewdata_isanswerd'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='todays_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
