# Generated by Django 3.1.3 on 2021-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0013_remove_interviewdata_isanswerd'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='marks_in_perc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
