# Generated by Django 3.1.3 on 2021-05-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0014_interviewdata_todays_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdata',
            name='todays_date',
        ),
    ]
