# Generated by Django 3.1.3 on 2021-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0015_remove_interviewdata_todays_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='today_date',
            field=models.DateField(default=(1997, 10, 19)),
            preserve_default=False,
        ),
    ]
