# Generated by Django 3.1.3 on 2021-05-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0016_interviewdata_today_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdata',
            name='today_date',
        ),
    ]
